// uniapp/hzjvliao/pages/login/index.vue
<template>
	<view class="container" :style="{height:windowHeight+'px'}">
		<image class="loading" src="/static/imgs/login.jpg" v-show="loading"></image>
		<view class="topBox">
			<image class="logo" src="/static/imgs/logo.png"></image>
			<text class="logoText">欢迎,请登录</text>
		</view>
		<view class="loginBox">
			<view class="inputBox">
				<image src="/static/imgs/tel.png" mode="scaleToFill" class="icon"></image>
				<input type="number" v-model="tel" class="formValue" placeholder='请输入手机号' placeholder-class="placeholder"/>
			</view>
			<view class="inputBox">
				<image src="/static/imgs/msg.png" mode="contain" class="icon"></image>
				<input type="number" v-model="code" class="formValue" placeholder='请输入验证码' placeholder-class="placeholder"/>
				<button class="codeBtn" @click="getCode">{{timer?time+'s':'获取验证码'}}</button>
			</view>
			<button class="loginBtn" @click="login()">登陆</button>
			<button class="loginBtn wechatBtn" @click="wechatLogin">微信登陆</button>
			<button class="loginBtn appleBtn" @click="appleLogin" v-show="appleShow">
				<image src="/static/imgs/ios.png" class="apple_icon"></image>通过苹果登陆
			</button>
		</view>
	</view>
</template>

<script>
	import {apiUrl} from '../../config';
	export default {
		data() {
			return {
				tel:'',
				code:'',
				time:60,
				timer:null,
				wechatInstall:true,
				loading:false,
				appleShow:false,
				windowHeight:650
			}
		},
		onLoad: function() {
			let {type,account,password} = uni.getStorageSync('account');

			if (type == 'wechat') {
				this.wechatLogin();
			}else if(type == 'apple'){
				this.appleLogin();
			}else if(type == 'tel'){
				this.tel = account;
				this.code = true;
				this.login(password);
			}

			uni.getSystemInfo({
				success:({system,windowHeight})=>{
					this.windowHeight = windowHeight;
					let [ios,version] = system.toLowerCase().split(' ');
					if((ios=='ios') && version>13){
						this.appleShow = true;
					}
				}
			})
		},
		methods: {
			wechatLogin:function(){
				uni.login({
				  provider: 'weixin',
				  success: (loginRes) => {
				    uni.getUserInfo({
				      provider: 'weixin',
				      success: ({userInfo}) => {
						  this.loading = true;
						  uni.request({
						  	url:apiUrl.wechatlogin,
						  	method: 'POST',
						  	data: {
								userinfo:{
								  openid:userInfo.openId,
								  nickname:userInfo.nickName,
								  sex:userInfo.gender,
								  headimgUrl:userInfo.avatarUrl,
								  unionid:userInfo.unionId,
								  city:userInfo.city,
								  country:userInfo.city,
								  province:userInfo.province
								}
						  	},
						  	success:({data:{error,data}}) => {
						  		if(error === 0){
									uni.setStorage({
										key:'account',
										data:{
											type:'wechat',
											remain:data
										}
									});
						  			uni.switchTab({
						  				url: '/pages/index/index'
						  			});
						  		}else{
									this.loginfail('登录失败,'+data);
						  		}
						  	},
						  	fail:(error) => {
								this.loginfail('登录失败'+error.errMsg);
							}
						  })
				      }
				    });
				  }
				});
			},
			appleLogin:function(){
				uni.login({  
				    provider: 'apple',  
				    success: (loginRes) => {
				        uni.getUserInfo({
				            provider: 'apple',  
				            success({userInfo}) {
								this.loading = true;
								uni.request({
									url:apiUrl.applelogin,
									method: 'POST',
									data: {
										userinfo:{
											openid:userInfo.openId,
											nickname:userInfo.familyName,
											email:userInfo.email
										}
									},
									success:({data:{error,data}}) => {
										if(error === 0){
											uni.setStorage({
												key:'account',
												data:{
													type:'apple',
													remain:data
												}
											});
											uni.switchTab({
												url: '/pages/index/index'
											});
										}else{
											this.loginfail('登录失败,'+data);
										}
									},
									fail:(error) => {
										this.loginfail('登录失败,请稍后再试');
									}
								})
				            }  
				        })  
				    },  
				    fail: (error) => {  
				        this.loginfail('登录失败'+error.errMsg);
				    }  
				});  
			},
			login:function(password = ''){
				if(!this.code){
					uni.showToast({
						icon:'none',
						title: '请填写验证码'
					});
					return;
				}
				this.loading = true;
				uni.request({
					url:apiUrl.checkcode,
					method: 'POST',
					data: {
						code:this.code,
						tel:this.tel,
						password
					},
					success:({data:{error,data}}) => {
						if(error === 0){
							uni.setStorage({
								key:'account',
								data:{
									type:'tel',
									account:this.tel,
									password:data.password,
									remain:data.remain
								}
							});
							uni.switchTab({
								url: '/pages/index/index'
							});
						}else{
							this.loginfail('登录失败,'+data);
						}
					},
					fail:(error) => {
						this.loginfail('登录失败,'+error.errMsg);
					}
				})
			},
			getCode:function(){
				if(!this.tel){
					uni.showToast({
						icon:'none',
						title: '请填写手机号'
					});
					return;
				}
				uni.request({
					url:apiUrl.sendcode,
					method: 'POST',
					headers: {
						Accept: 'application/json',
						'Content-Type': 'application/json'
					},
					data:{
						tel:this.tel
					},
					success:({data:{error,data}}) => {
						if(error === 0){
							this.timer = setInterval(() => {
								this.time -= 1;
								if(this.time === 0){
									clearInterval(this.timer);
									this.time = 60;
									this.timer = null;
								}
							}, 1000);
						}else{
							uni.showToast({
								icon:'none',
								title: '获取验证码失败,'+data
							})
						}
					},
					fail:(error) => uni.showToast({icon:'none',title: '获取验证码失败,'+error.errMsg})
				})
			},
			loginfail:function(msg){
				uni.showToast({
					icon:'none',
					title: msg
				});
				uni.removeStorage({
				    key: 'account'
				});
				this.loading = false;
			}
		}
	}
</script>

<style lang="scss">
	.container {
		display: flex;
		flex-direction: column;
		background-image:url(/static/imgs/login_bg.jpg);
		background-size: cover;
		overflow: hidden;
	}
	
	.loading{
		position: absolute;
		width:100%;
		height:100%;
		left: 0;
		top:0;
		z-index:1;
	}
	
	.topBox {
		flex: 1;
		height: 436rpx;
		width:750rpx;
		text-align: center;
	}
	
	.logo {
		height: 200rpx;
		width: 200rpx;
		margin: 0 auto;
		margin-bottom: 50rpx;
		padding-top: 80rpx;
	}
	
	.logoText {
        color:#fff;
        font-size:36rpx;
    }
	
	.loginBox {
	    flex:2;
	    border-top-left-radius:30rpx;
	    border-top-right-radius:30rpx;
		background: url(/static/imgs/loginbox_bg.jpg);
		background-size: cover;
		padding: 80rpx 45rpx;
	}
	
	.inputBox {
	    height:100rpx;
	    border-radius:20rpx;
	    background-color:#fff;
		display: flex;
	    align-items:center;
	    margin-bottom:50rpx;
		overflow: hidden;
	}
	
	.icon {
	    width:50rpx;
	    height:50rpx;
		margin:0 28rpx;
	}
	
	.formValue {
	    flex:1;
	    height:100rpx;
	    font-size:30rpx;
	    color:#6886b4;
	    background-color:#fff;
	}
	
	.codeBtn {
	    width:220rpx;
	    height:70rpx;
	    background-color:#00a3ff;
		color:#fff;
		font-size:30rpx;
	    border-radius:20rpx;
		line-height: 70rpx;
		margin-right:20rpx;
	}

	.loginBtn {
		color:#fff;
	    height:88rpx;
		line-height: 88rpx;
	    border-radius:60rpx;
		font-size: 38rpx;
		background: url(/static/imgs/btnbg1.png);
		background-size: cover;
	}
	
	.wechatBtn {
		margin-top: 190rpx;
		background: #04BE02;
	}
	
	.appleBtn {
		margin-top: 30rpx;
		background: #000;
	}
	.apple_icon{
		width: 62rpx;
		height: 88rpx;
		margin-right: 10rpx;
		display: inline-block;
		vertical-align: bottom;
	}
</style>

// react/hzjvliao/src/views/Login/index.js
import React, { Component } from 'react';
import { View, Text, TouchableOpacity, StyleSheet,SafeAreaView,ImageBackground,Image,TextInput,Keyboard,StatusBar,ActivityIndicator,Modal,AsyncStorage } from 'react-native';
import {Toast,TopView} from '../../components/teaset';
import * as WeChat from 'react-native-wechat';
import {apiUrl} from '../../config';
import {px2dp} from '../../util';
export default class HomeScreen extends Component {
    state = {
        tel:'',
        code:'',
        time:60,
        timer:null,
        wechatInstall:true,
        loading:false,
    }

    componentDidMount() {
        try {
            WeChat.registerApp('wx85a7fbb0bd4c6e3c');
            WeChat.isWXAppInstalled().then((res)=>{
                this.setState({wechatInstall:res})
            });
        } catch (e) {
            console.error(e);
        }
        Keyboard.addListener(
            'keyboardDidHide',
            ()=>{
                Keyboard.dismiss();
            }
        );
    }

    login(){
        let {code,tel} = this.state;
        if(!code){
            Toast.fail('请填写验证码');
            return;
        }
        fetch(apiUrl.checkcode,{
            method: 'POST',
            headers: {
                Accept: 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                code,
                phone:tel
            })
        })
        .then((response) => response.json())
        .then(({error,data}) => {
            if(error === 0){
                AsyncStorage.setItem('remain', data);
                this.props.navigation.replace('Index');
            }else{
                Toast.fail('登录失败,'+data)
            }
        })
        .catch((error) => Toast.fail('登录失败,'+error))
    }
    getCode(){
        let {timer,time,tel} = this.state;
        if(!tel){
            Toast.fail('请填写手机号');
            return;
        }
        fetch(apiUrl.sendcode,{
            method: 'POST',
            headers: {
                Accept: 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                tel
            })
        })
        .then((response) => response.json())
        .then(({error,data}) => {
            if(error === 0){
                timer = setInterval(() => {
                    time -= 1;
                    this.setState({time});
                    if(time === 0){
                        clearInterval(timer);
                        this.setState({time:60,timer:null});
                    }
                }, 1000);
                this.setState({timer});
            }else{
                Toast.fail('获取验证码失败,'+data)
            }
        })
        .catch((error) => Toast.fail('获取验证码失败,'+error))
    }
    wechatLogin(){
        // AsyncStorage.setItem('remain', "3");
        // this.props.navigation.replace('Index');
        // return;
        if(!this.state.wechatInstall){
            Toast.fail('您未安装微信app');
            return;
        }
        this.setState({loading:true});
        WeChat.sendAuthRequest("snsapi_userinfo").then(({errCode,code})=>{
            if(errCode == 0){
                fetch(apiUrl.wechatLogin,{
                    method: 'POST',
                    headers: {
                        Accept: 'application/json',
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({
                        code
                    })
                })
                .then((response) => response.json())
                .then(({error,data}) => {
                    if(error === 0){
                        AsyncStorage.setItem('remain', data);
                        this.props.navigation.replace('Index');
                    }else{
                        this.setState({loading:false});
                        Toast.fail('登录失败,'+data);
                    }
                })
                .catch((error) => {
                    this.setState({loading:false});
                    Toast.fail('登录失败,'+error);
                })
            }else{
                this.setState({loading:false});
            }
        });
    }
    render() {
        let {tel,code,timer,time,loading} = this.state;
        return (
            <TopView>
            <SafeAreaView style={styles.container}>
                <StatusBar backgroundColor="#3d80e6"/>
                <ImageBackground source={require("../../imgs/login_bg.jpg")} style={styles.bg}>
                    <View style={styles.topBox}>
                        <Image
                            style={styles.logo}
                            resizeMode='contain'
                            source={require("../../imgs/logo.png")}
                        />
                        <Text style={styles.logoText}>欢迎,请登录</Text>
                    </View>
                    <View style={styles.loginBox}>
                        <ImageBackground source={require("../../imgs/loginbox_bg.jpg")} style={{...styles.bg,justifyContent:'space-around'}}>
                            <View>
                                <View style={styles.inputBox}>
                                    <Image style={styles.icon} resizeMode='contain' source={require("../../imgs/tel.png")}/>
                                    <TextInput style={styles.formValue} clearButtonMode='while-editing' value={tel}
                                        onChangeText={tel => this.setState({tel})} placeholder='请输入手机号' keyboardType='numeric' placeholderTextColor='#6886b4' returnKeyType="done"/>
                                </View>
                                <View style={styles.inputBox}>
                                    <Image style={styles.icon} resizeMode='contain' source={require("../../imgs/msg.png")}/>
                                    <TextInput style={styles.formValue} clearButtonMode='while-editing' value={code}
                                        onChangeText={code => this.setState({code})} placeholder='请输入验证码' keyboardType='numeric' placeholderTextColor='#6886b4' returnKeyType="done"/>
                                    <TouchableOpacity
                                        style={styles.codeBtn} 
                                        activeOpacity={0.8}
                                        onPress={() =>this.getCode()}
                                    >
                                        <Text style={styles.codeText}>{timer?time+'s':'获取验证码'}</Text>
                                    </TouchableOpacity>
                                </View>

                                <TouchableOpacity style={styles.loginBtn} activeOpacity={1} onPress={() => this.login()}>
                                    <ImageBackground source={require("../../imgs/btnbg1.png")} style={styles.bg}>
                                        <Text style={styles.btnText}>登录</Text>
                                    </ImageBackground>
                                </TouchableOpacity>
                            </View>

                            <TouchableOpacity style={styles.loginBtn} activeOpacity={1} onPress={() => this.wechatLogin()}>
                                <ImageBackground source={require("../../imgs/btnbg2.png")} style={styles.bg}>
                                    <Text style={styles.btnText}>微信登录</Text>
                                </ImageBackground>
                            </TouchableOpacity>
                        </ImageBackground>
                    </View>
                </ImageBackground>
                <Modal
                    animationType="none"
                    visible={loading}
                    transparent={true}
                    style={styles.loading}
                >
                    <ImageBackground source={require("../../imgs/login.jpg")} style={styles.bg}>
                    </ImageBackground>
                </Modal>
            </SafeAreaView>
            </TopView>
        )
    }
}

const styles = StyleSheet.create({
    container:{
        flex: 1
    },
    bg:{
        flex:1,
        resizeMode: "cover",
        justifyContent: "center",
        overflow:'hidden'
    },
    topBox:{
        flex:1,
        justifyContent:'center',
        alignItems:'center'
    },
    logo:{
        width:px2dp(204),
        height:px2dp(204),
        marginBottom:px2dp(50)
    },
    logoText:{
        color:'#fff',
        fontSize:px2dp(36)
    },
    loginBox:{
        flex:2,
        borderTopLeftRadius:px2dp(30),
        borderTopRightRadius:px2dp(30)
    },
    inputBox:{
        height:px2dp(100),
        borderRadius:px2dp(20),
        backgroundColor:'#fff',
        flexDirection:'row',
        alignItems:'center',
        marginHorizontal:px2dp(30),
        paddingHorizontal:px2dp(28),
        marginBottom:px2dp(50)
    },
    icon:{
        width:px2dp(50),
        height:px2dp(50)
    },
    formValue:{
        flex:1,
        height:px2dp(100),
        fontSize:px2dp(30),
        color:'#6886b4',
        backgroundColor:'#fff',
        borderRadius:px2dp(20),
        paddingHorizontal:px2dp(30),
        paddingVertical:px2dp(18)
    },
    codeBtn:{
        width:px2dp(220),
        height:px2dp(70),
        backgroundColor:'#00a3ff',
        borderRadius:px2dp(20),
        justifyContent:'center'
    },
    codeText:{
        color:'#fff',
        fontSize:px2dp(30),
        textAlign:'center'
    },
    loginBtn:{
        height:px2dp(100),
        borderRadius:px2dp(20),
        marginHorizontal:px2dp(30),
        justifyContent:'center',
        overflow:'hidden'
    },
    btnText:{
        color:'#fff',
        textAlign:'center',
        fontSize: px2dp(36)
    },
    loading:{
        position:'absolute',
        flex:1,
        zIndex:100
    }
})
